name: cardiac
favicon: null
layout_spectrum: 0.9343132562935352
typography_spectrum: 0.6713124373927712
title: Cardiac Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0710'
    - '#54635e'
    - '#e8e9e1'
    - '#ae857f'
    - '#a4bdac'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
